### ISSUE TITLE
v.1.1.4 - no charging status is shown

### ISSUE THREAD

**Issue by sanchosk** [WJDDesigns/Ultra-Vehicle-Card#15] opened 2024-08-05 20:23 UTC
![image](https://github.com/user-attachments/assets/8904db01-2c61-401b-a217-aa8be9e7be12)
No idea what's wrong, but suddenly my battery level is not shown.

**Comment by WJDDesigns** [comment] 2024-08-05 20:24
Please make sure you redownload the latest version. Then you need to restart Home Assistant and clear your browser cache.

**Comment by sanchosk** [comment] 2024-08-05 20:41
> Please make sure you redownload the latest version. Then you need to restart Home Assistant and clear your browser cache.

I did try to re-download, even recreate a new section from scratch. Both my cars now do not show the charge bar.

**Comment by WJDDesigns** [comment] 2024-08-05 20:44
Can you try a different browser for testing. Also delete the entity and save, then re add as well. We've had numerous people try the new update with success so it might be a caching issue?

**Comment by sanchosk** [comment] 2024-08-05 20:56
Cleared cache, tried private browsing with removed cookies and cache, opened in MS Edge (only non-firefox browser available at the moment), all behave the same - no charging status, bar, range.

**Comment by sanchosk** [comment] 2024-08-05 20:56
![image](https://github.com/user-attachments/assets/39a67854-6e19-4204-a0f6-b4aaa50d9f41)
This might be the issue...

**Comment by sanchosk** [comment] 2024-08-05 21:00
Re-downloaded 1.1.1, refreshed the page and the status is there :(

**Comment by WJDDesigns** [comment] 2024-08-05 21:09
> Re-downloaded 1.1.1, refreshed the page and the status is there :(

What is your plugin and HA version?

**Comment by sanchosk** [comment] 2024-08-05 21:26
Tested on Linux Firefox and Chromium, with cleared cache and cookies.
Home assistant:
    Core 2024.7.4
    Supervisor 2024.06.2
    Operating System 12.4
    Frontend 20240710.0
![image](https://github.com/user-attachments/assets/5dcf7ce4-404c-45a3-b58e-f34e7353dc87)
I try to keep everything on latest stable, so...

**Comment by Gavisann** [comment] 2024-08-05 21:47
Seeing this now for ICE vehicles as well. 

I believe it's due to `level_entity` being used in the editor and `x__level_entity` being used in the card. 

Here's an example with level manually switched to `level_entity` instead of `fuel_level_entity` and range left as is and showing undefined.

![image](https://github.com/user-attachments/assets/09d8dd0b-72ba-483b-bb45-9399f7cc418c)


Not sure how you would like to address it so didn't modify any code :)

**Comment by Gavisann** [comment] 2024-08-05 21:52
Wait my mistake. My editor.js is stale. HASS seems to cache it longer than I would expect...

**Comment by WJDDesigns** [comment] 2024-08-05 21:52
> Seeing this now for ICE vehicles as well. 
> 
> 
> 
> I believe it's due to `level_entity` being used in the editor and `x__level_entity` being used in the card. 
> 
> 
> 
> Here's an example with level manually switched to `level_entity` instead of `fuel_level_entity` and range left as is and showing undefined.
> 
> 
> 
> ![image](https://github.com/user-attachments/assets/09d8dd0b-72ba-483b-bb45-9399f7cc418c)
> 
> 
> 
> 
> 
> Not sure how you would like to address it so didn't modify any code :)

I appreciate the looking into. Once I'm in the command center I'll make the changes that need to be made. Oddly mine is working here so hard to replicate.

**Comment by WJDDesigns** [comment] 2024-08-05 23:53
<img width="926" alt="Screenshot 2024-08-05 at 7 49 31 PM" src="https://github.com/user-attachments/assets/72c6ab64-5696-488a-abaa-5d40fc06b288">

I just deleted the integration and wiped it all out of my Home Assistant install then reinstalled. I added each of my vehicle entities one by one and had no issues. I can keep this open if we have more of these issues but I can't replicate.

**Comment by Gavisann** [comment] 2024-08-06 01:09
I was able to get it working with a lot of manual cache clearing... Really annoying how HASS handles that, but can confirm it's working applied over my previously installed version.

**Comment by sanchosk** [comment] 2024-08-06 05:57
I did something strange - switched back to 1.1.1, checked android app - the bar is back. Switched to 1.1.4, the bar remains on android app, PC shows no bar. Force-stopped android app, started again - bar is gone.
I'll try to wipe it completely and re-setup...

**Comment by sanchosk** [comment] 2024-08-06 06:06
OK, my steps:
- removed the HACS integration
- restarted HA
- redownloaded the integration, version 1.1.4
- set up one car - no bar is shown
- switched to 1.1.1
- charge bar is shown
:( Is there any JS or inspection or something I can do to provide more info?

**Comment by sanchosk** [comment] 2024-08-06 06:09
One more info - my HACS version is 1.34.0. No idea how I can update that :)

**Comment by AlexandreLogist** [comment] 2024-08-06 06:57
> One more info - my HACS version is 1.34.0. No idea how I can update that :)

That is the latest version, so you are fine :_)

**Comment by WJDDesigns** [comment] 2024-08-06 13:20
So is it safe to close this, seems like a caching issue is always the cause. I had this issue on phone app until I went into the settings and reset frontend cache on app.

**Closed** 2024-08-06 19:29 UTC
